[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-Clinker-flavor=ld.lld"]

# [target.x86_64-pc-windows-msvc]
# linker = "lld-link.exe"
# rustflags = ["-Ctarget-feature=+crt-static"]

# [build]
# rustc-wrapper = "C:\\Users\\15126\\.cargo\\bin\\sccache.exe"

[unstable]
gc = true

# [source.crates-io]
# registry = "https://github.com/rust-lang/crates.io-index"

# 指定镜像
# replace-with = 'rsproxy'

# 中国科学技术大学
# [source.ustc]
# registry = "https://mirrors.ustc.edu.cn/crates.io-index"

# 添加 rsproxy 源
# [source.rsproxy]
# registry = "https://rsproxy.cn/crates.io-index"

# 添加 rsproxy 源的备用下载地址
# [source.rsproxy-sparse]
# registry = "sparse+https://rsproxy.cn/index/"
