[package]
name = "rust"
version = "0.1.0"
edition = "2021"
default-run = "rust"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
mime = "0.3"
futures-util = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
tracing-attributes = "0.1.27"
tokio = { version = "1.43", features = ["rt-multi-thread", "macros", "net", "fs"], default-features = false }
poem = { version = "3.1.6", features = ["rustls", "server", "multipart", "tempfile", "eyre06", "tokio-metrics", "websocket"], default-features = false }
async-graphql = { version = "7.0.14", features = ["decimal", "bigdecimal", "time", "chrono", "chrono-tz", "smol_str", "tokio-sync"] }
smol_str = { version = "0.3", features = ["serde"] }
slab = "0.4"
chrono = { version = "0.4", features = ["serde"] }
# anyhow = "1.0"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "mysql", "uuid", "chrono", "time", "bigdecimal", "rust_decimal", "json"] }
dotenv = "0.15"
rust-s3 = { version = "0.35.1", features = ["tokio-rustls-tls"], default-features = false }
imstr = { version = "0.2", features = ["serde"] }
jwt = "0.16"
sha2 = "0.10"
sha1 = "0.10"
hmac = { version = "0.12", features = ["reset"] }
# protobuf = "3.7.1"
hex-literal = "0.4"
hex = "0.4"
base64 = "0.22"
utf8_slice = "1.0"
derive-new = "0.6"
reqwest = { version = "0.12.9", features = ["rustls-tls", "json", "multipart", "stream"], default-features = false }
encoding_rs = "0.8"
urlencoding = "2.1"
url = "2.5"
# sqlformat = "0.3.5"
smallvec = { version = "1.13", features = ["union", "serde"] }
# downcast-rs = "1.2"
uuid = { version = "1.11", features = ["serde", "v4", "fast-rng"] }
deadpool = "0.12"
deadpool-redis = "0.18"
redis = { version = "0.28", features = ["tokio-comp"], default-features = false }
# pin-project = "1.1"
bigdecimal = "0.4"
time = "0.3"
rust_decimal = "1.36"
rust_decimal_macros = "1.36"
# enum_dispatch = "0.3.13"
# pin-project-lite = "0.2"
# rayon = "1.10"
regex = "1.11"
# yarte = "0.15.7"
image = { version = "0.25.5", features = ["webp"] }
delay_timer = "0.11.6"
num-traits = "0.2"
fast_chemail = "0.9"
http = "1.1"
futures = "0.3"
aes = "0.8"
cbc = { version = "0.1", features = ["alloc"]}
function_name = "0.3.0"
enum-iterator = "2.1"
derive_more = { version = "1.0.0", features = ["full"] }
derive_builder = "0.20"
strum = { version = "0.26", features = ["derive"] }
itertools = "0.14.0"
color-eyre = "0.6.3"

# 安全地使用无proc宏的自引用结构
# self_cell = "1.1"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6.0"

# [build.dependencies]
# protobuf-codegen = "3.7.1"

[[bin]]
name = "rust"
path = "src/main.rs"

[profile.release]
panic = "unwind"

[[bin]]
name = "schema"
path = "src/schema.rs"
